name: Cabin CI

on:
  push:
    branches: [ master ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      analyzer: ${{ steps.filter.outputs.analyzer }}
      frontend: ${{ steps.filter.outputs.frontend }}
      arduino_software: ${{ steps.filter.outputs.arduino_software }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          analyzer:
            - 'analyzer/**'
          frontend:
            - 'frontend/**'
          arduino_software:
            - 'Arduino_Software/**'

  halt_system:
    needs: changes
    if: ${{ needs.changes.outputs.analyzer == 'true' || needs.changes.outputs.frontend == 'true' || needs.changes.outputs.arduino_software == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H thanksgiving.dinnen.engineering >> ~/.ssh/known_hosts
      - name: Stop Pi
        run: ssh pi@thanksgiving.dinnen.engineering "sudo systemctl stop analyzer"

  build_arduino:
    needs: [changes, halt_system]
    if: ${{ needs.changes.outputs.arduino_software == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H thanksgiving.dinnen.engineering >> ~/.ssh/known_hosts
      - name: Build Arduino
        run: |
          ssh pi@thanksgiving.dinnen.engineering "cd /home/pi/Thanksgiving_Intranet/Arduino_Software; git pull; make"

  build_analyzer:
    needs: [changes, halt_system]
    if: ${{ needs.changes.outputs.analyzer == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H thanksgiving.dinnen.engineering >> ~/.ssh/known_hosts
      - name: Build Analyzer
        run: |
          cd analyzer
          export PATH=$PATH:$(go env GOPATH)/bin
          make compile
          rsync -z --progress ./build/analyzer-linux-arm-5 pi@thanksgiving.dinnen.engineering:~/go/bin/analyzer

  build_frontend:
    needs: [changes, halt_system]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H thanksgiving.dinnen.engineering >> ~/.ssh/known_hosts
      - name: Build Frontend
        run: |
          cd frontend
          yarn
          yarn build
          yarn upload
          
  start_system:
    needs: [changes, halt_system, build_arduino, build_analyzer, build_frontend]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H thanksgiving.dinnen.engineering >> ~/.ssh/known_hosts
      - name: Start Pi
        run: ssh pi@thanksgiving.dinnen.engineering "sudo systemctl start analyzer"